config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  resources :movies do
    collection do
      get 'search'
    end
    resources :reviews, except: [:index, :show]
  end
  root 'movies#index'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  searchkick
  belongs_to :user
  has_many :reviews
  has_attached_file :image, styles: { medium: "400x600>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :user_id, uniqueness: {scope: :movie_id, message: "You can't review a product more than once"}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :movies
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  
  def search
    if !params[:search].blank?
      @movies = Movie.search(params[:search])
    else
      @movies = Movie.all
    end
  end

  def index
    @movies = Movie.all
  end

  def show
    if @movie.reviews.blank?
      @avg_review = 0
    else
      @avg_review = @movie.reviews.average(:rating).round(2)
    end
    if current_user
      @reviewed = current_user.reviews.find_by(movie_id: params[:id])
    end
  end

  def new
    @movie = current_user.movies.build
  end

  def edit
  end

  def create
    @movie = current_user.movies.build(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :movie_length, :image, :director, :rating, :img_url)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_movie
  def index
    @reviews = Review.all
  end

  def show
  end

  def new
    @review = Review.new
  end

  def edit
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.movie_id = @movie.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to @movie, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @movie, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    
    def set_review
      @review = Review.find(params[:id])
    end

    def set_movie
      @movie = Movie.find(params[:movie_id])
    end
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Movie Reviews", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <li><%= link_to "New Movie", new_movie_path, class: "active" %></li>
          <li><%= link_to "Account", edit_user_registration_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sign Out", destroy_user_session_path, class: "active", method: :delete, data: {confirm: 'Are you sure that you wanna Sign Out?'} %></li>
        </ul>
        <% else %>
        <ul class="nav navbar-nav">
          <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
        </ul>
        <% end %>
      </ul>
      <%= form_tag search_movies_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
        <p>
          <%= text_field_tag :search, params[:search], class: 'form-control'%>
          <%= submit_tag 'Search', name: nil, class: 'btn btn-default'%>
        </p>
      <% end %> 
      
   </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class:"alert alert-info" )%>
		<% end %>
		<%= yield %>
	</div>


</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, html: { multipart: true } do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :movie_length %><br>
    <%= f.text_field :movie_length, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :director %><br>
    <%= f.text_field :director, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :rating %><br>
    <%= f.text_field :rating, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label 'Reserve Image Url' %><small style='color: grey'>&nbsp;*Not required</small><br>
    <%= f.text_field :img_url, class: 'form-control' %>
  </div>

  <div class="form-actions">
    <%= f.submit class: 'bbtn' %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<div class="col-md-6 col-md-offset-3">	
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h1>Editing Movie</h1>
			</div>
			<div class="panel-body">		
				<%= render 'form' %>
			</div>
			<div class="panel-footer">
				<%= link_to 'Back', movies_path %>
			</div>
		</div>
	</div>
</div>

app/views/movies/index.html.erb
<% if !user_signed_in? %>
  <div class="jumbotron">
    <h1>Your Favorite Movies Revied</h1>
    <p>Hashtag hoodie mumblecore selfies. Authentic keffiyeh leggings Kickstarter, narwhal jean shorts XOXO Vice Austin cardigan. Organic drinking vinegar freegan pickled.</p>
    <p><%= link_to "Sign Up To Write A Review", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
  </div>
<% end %>

<div class="row">
  <% @movies.each do |movie|%>
    <div class="col-sm-6 col-md-3">
      <% if movie.img_url.blank? %>
        <div class="thumbnail">
          <%= link_to (image_tag movie.image.url(:medium), class: 'image'), movie %>
        </div>
      <% else %>
        <div class="thumbnail">
          <%= link_to (image_tag movie.img_url), movie %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/movies/new.html.erb
<div class="col-md-6 col-md-offset-3">	
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h1>New Movie</h1>
			</div>
			<div class="panel-body">		
					<%= render 'form' %>
			</div>
			<div class="panel-footer">
				<%= link_to 'Back', movies_path %>
			</div>
		</div>
	</div>
</div>

app/views/movies/search.html.erb
<div class="row">
  <% @movies.each do |movie|%>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag movie.image.url(:medium), class: 'image'), movie %>
      </div>
    </div>
  <% end %>
</div>

app/views/movies/show.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		<div class="row">
			<div class="col-md-4">
				<% if @movie.img_url.blank? %>
	        		<%= image_tag @movie.image.url(:medium)%>
	   			<% else %>
	   				<%= image_tag @movie.img_url%>
	            <% end %>

				<div class="star-rating" data-score= <%= @avg_review %>><b><%= @avg_review %></b> | </div>
				<em><%= @movie.reviews.length%> reviews</em>
				<div class="table-responsive">
					<table class="table">
						<tbody>
							<tr>
								<td><strong>Title:</strong></td>
								<td><%= @movie.title %></td>
							</tr>
							<tr>
								<td><strong>Description:</strong></td>
								<td><%= @movie.description %></td>
							</tr>
							<tr>
								<td><strong>Movie Length:</strong></td>
								<td><%= @movie.movie_length %></td>
							</tr>
							<tr>
								<td><strong>Director:</strong></td>
								<td><%= @movie.director %></td>
							</tr>
							<tr>
								<td><strong>Rating:</strong></td>
								<td><%= @movie.rating %></td>
							</tr>
						</tbody>
					</table>
				</div>	
			</div>
			<div class="col-md-7 col-md-offset-1">
				<h1 class='review_title'><%= @movie.title%></h1>
				<p><%= @movie.description%></p>

				<% if @movie.reviews.blank? %>
					<h3> No reviews just yet, would you like to add the first!</h3>
				<% else %>
					<% @movie.reviews.each do |review|%>
						<div class="reviews">
							<p><%= review.user.email%></p>
							<div class='star-rating' data-score= <%= review.rating%>></div>
							<p><%= review.comment%></p>
							<% if review.user == current_user %>
								<%= link_to 'Edit', edit_movie_review_path(review.movie, review)%>
							<% end %>
						</div>
					<% end %>
				<% end %>
				<% if @reviewed.blank? %>
					<%= link_to 'Write a Review', new_movie_review_path(@movie), class: 'btn btn-danger btn-lg btn-block ' %>
				<% end %>
			</div>
		</div>
	</div>
	<div class="panel-footer">
		<%= link_to 'Edit', edit_movie_path(@movie) %> |
		<%= link_to 'Back', movies_path %>
		<% if @movie.user == current_user %>
			| <%= link_to 'Destroy', movie_path, method: :delete, data: {confirm: 'Are you sure?'} %>
		<% end %>
	</div>
</div>


<script>
    $('.star-rating').raty({
      path: '',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>

app/views/reviews/_form.html.erb
<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div id='star-rating'></div>
  </div>
  <div class="form-group">
    <%= f.label :comment %><br>
    <%= f.text_area :comment, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'bbtn' %>
  </div>
<% end %>


<script>
  $('#star-rating').raty({
    path: '',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">	
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-heading">	
				<h1>Editing Review</h1>
			</div>
			<div class="panel-body">		
					<%= render 'form' %>
			</div>
			<div class="panel-footer">
				<%= link_to 'Back', movie_path(@movie) %>
			</div>
		</div>
	</div>
</div>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">	
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-heading">	
				<h1>New Review</h1>
			</div>
			<div class="panel-body">		
					<%= render 'form' %>
			</div>
			<div class="panel-footer">
				<%= link_to 'Back', movie_path(@movie) %>
			</div>
		</div>
	</div>
</div>